apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: avocado-
resources:
- deployment.yaml
# - service.yaml
# - ingress.yaml

vars:
- name: IMAGE_TAG
  objref:
    kind: Deployment
    name: client
    apiVersion: apps/v1
  fieldref:
    fieldpath: spec.template.spec.containers[0].image