apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: avocado-
resources:
- deployment.yaml
# - service.yaml
# - ingress.yaml

vars:
- fieldref:
    fieldPath: spec.template.spec.containers[0].image
  name: IMAGE_TAG
  objref:
    apiVersion: apps/v1
    kind: Deployment
    name: client
images:
- name: avocado-client
  newName: 749740892195.dkr.ecr.ap-northeast-2.amazonaws.com/avocado-client
  newTag: "44"
