spring.webflux.base-path: /api/member
r2dbc:
  host: a07c6127933494883b1ce18e5a21f697-895151877.ap-northeast-2.elb.amazonaws.com
  username: root
  password: yasim506
  port: 3306
  database: member

spring:
  kafka:
    bootstrap-servers: a62e5b172168c40419f9a1af18763a94-214776296.ap-northeast-2.elb.amazonaws.com:9094
    purchase-history-config:
      topic: test-purchase-history1
    member-event-config:
      topic: test-member-event1

oauth2:
  kakao:
    client_id: 34142e13b083ba5a3335330cc8cdaf5e
    client_secret: S9Yo9z0PJ5CKj8HAMH2QwJsPqxYm6ICc
#    redirect_uri: http://localhost:8080/member/kakao/redirect
    redirect_uri: http://k8s-avocado-c6c0ca3c6e-209771398.ap-northeast-2.elb.amazonaws.com/api/member/kakao/redirect
    token_uri: https://kauth.kakao.com/oauth/token
    authorization_uri: https://kauth.kakao.com/oauth/authorize

jwt:
  issuer: avocado.com
  secret: e52713a2bd59e655ffd78ed74fafc5b29a2001d586949e55792e2f1a5b1f3d8ffb9d132354932bdf
  access_expiration: 21600000
  refresh_expiration: 1296000000

front:
  redirect_uri: http://localhost:3000/login/oauth-redirect
#  redirect_uri: http://k8s-avocado-c6c0ca3c6e-209771398.ap-northeast-2.elb.amazonaws.com/login/oauth-redirect

logging:
  level:
#    io.asyncer.r2dbc.mysql.client: TRACE
    org.springframework.r2dbc.core: DEBUG