#r2dbc:
#  host: localhost
#  username: root
#  password: ssafy
#  port: 3306
#  database: avocado_member
r2dbc:
  host: a4231aa8b5f6f4c258756076545155f8-632431843.ap-northeast-2.elb.amazonaws.com
  username: root
  password: root
  port: 3306
  database: member
oauth2:
  kakao:
    client_id: 34142e13b083ba5a3335330cc8cdaf5e
    client_secret: S9Yo9z0PJ5CKj8HAMH2QwJsPqxYm6ICc
#    redirect_uri: http://localhost:8080/kakao/redirect
    redirect_uri: http://a7068970118a34e5db1e15df1293f5d2-1354981975.ap-northeast-2.elb.amazonaws.com/kakao/redirect
    token_uri: https://kauth.kakao.com/oauth/token

jwt:
  issuer: avocado.com
  secret: e52713a2bd59e655ffd78ed74fafc5b29a2001d586949e55792e2f1a5b1f3d8ffb9d132354932bdf
  access_expiration: 21600000
  refresh_expiration: 1296000000

front:
#  redirect_uri: http://localhost:8080/redirect
  redirect_uri: http://a7068970118a34e5db1e15df1293f5d2-1354981975.ap-northeast-2.elb.amazonaws.com/redirect

logging:
  level:
#    io.asyncer.r2dbc.mysql.client: TRACE
    org.springframework.r2dbc.core: DEBUG