apiVersion: apps/v1
kind: Deployment
metadata:
  name: community
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: community
  template:
    metadata:
      labels:
        app: community
    spec:
      containers:
      - name: community
        image: avocado-community
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
