spring:
  datasource:
    url: jdbc:mysql://a07c6127933494883b1ce18e5a21f697-895151877.ap-northeast-2.elb.amazonaws.com:3306/product?serverTimezone=UTC&characterEncoding=UTF-8
    username: yasim
    password: yasim506
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: a62e5b172168c40419f9a1af18763a94-214776296.ap-northeast-2.elb.amazonaws.com:9094
    view-config:
      topic: test-view
    click-config:
      topic: test-click1
    cart-config:
      topic: test-cart
    purchase-history-config:
      topic: test-purchase-history1
    review-config:
      topic: test-review
    member-event-config:
      topic: test-member-event


server:
  servlet:
    context-path: /api/merchandise
#  tomcat:
#    accesslog:
#      enabled: true
#      directory: tomcat
#      suffix: .log
#      prefix: access_log
#      file-date-format: .yyyy-MM-dd
#      pattern: '%{yyyy-MM-dd HH:mm:ss}t %s %r %l %u'
#    basedir: /var/log

jwt:
  issuer: avocado.com
  secret: e52713a2bd59e655ffd78ed74fafc5b29a2001d586949e55792e2f1a5b1f3d8ffb9d132354932bdf
  access_expiration: 21600000
  refresh_expiration: 1296000000