spring:
  datasource:
    url: jdbc:mysql://a07c6127933494883b1ce18e5a21f697-895151877.ap-northeast-2.elb.amazonaws.com:3306/payment?serverTimezone=UTC&characterEncoding=UTF-8
    username: yasim
    password: yasim506
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  redis:
    host: a57b7bdd07e984044bce6a0784fa0b62-8549102.ap-northeast-2.elb.amazonaws.com
    port: 6379
    password: yasim506

server:
  servlet:
    context-path: /api/payment

kakao-pay:
  host: https://kapi.kakao.com
  admin-key: 3c11e4e624e930df14f2c8618a2b454a
  cid: TC0ONETIME

  url:
    api:
      ready: /v1/payment/ready
      approve: /v1/payment/approve
    handle:
      host: http://localhost:8080/api/payment #http://k8s-avocado-c6c0ca3c6e-209771398.ap-northeast-2.elb.amazonaws.com/api/payment
      approve: /approval/
      cancel: /cancel/
      fail: /fail/
    redirect:
      host: http://k8s-avocado-c6c0ca3c6e-209771398.ap-northeast-2.elb.amazonaws.com
      approval: /user/orderList
      cancel: /user/cartList
      fail: /404

jwt:
  issuer: avocado.com
  secret: e52713a2bd59e655ffd78ed74fafc5b29a2001d586949e55792e2f1a5b1f3d8ffb9d132354932bdf
  access_expiration: 21600000
  refresh_expiration: 1296000000